version: '3'
services:
  node:
    image: node:14.9.0-alpine3.10
    container_name: node
    volumes:
      - .:/app
    tty: true
    working_dir: /app
    ports:
      - 3000:3000
    command: npm start
